package com.sample
 
 import com.sample.model.Event;
 import com.sample.Bot;
//global com.sample.Bot globalBot;
declare Bot
	
end

declare Event
	@role(event)
end
 
rule "Event Received"
	when
		$newEvent: Event() from entry-point entrada
		
	then
		System.out.println("New Event received from: "+$newEvent.getTitle() );
end


rule "Light On" 
	when 
		$newEvent0: Event(title=="light",value<1000) from entry-point entrada 

	then 
		System.out.println("Light on"); 
		insert(new Event("light_on",1));
		
end

rule "Bot"
	when 
		$newEvent: Event(title=="light_on")
	then

        botFunction();
		System.out.println("Rule bot triggered");
end 

rule "Twitter"
	when 
		$newEvent: Event(title=="light_on")
	then

        twitterFunction();
		System.out.println("Rule twitter triggered");
end 


function twitterFunction(){
		Twitter twitter =new Twitter();
		twitter.send(" @pmoncadaisla acaba de entrar al laboratorio");
}
function botFunction(){
		Bot bot = new Bot();
		bot.send("Bienvenido al gsi ");

}